### PR TITLE
Add image carousel

### LINKED ISSUE #31: Add an image carousel to the Landing page
Followup to #19 to implement the image carousel with the preferred approach.

## Requirements

 - Add an image carousel to the bottom of the Landing page (meeting requirements outlined in #19)
 - @WillBAnders to collect pictures from SSD events

### PR DESCRIPTION
**Pull request by Brian-Magnuson**
Resolves #31. Adds an image carousel to the landing page. The image carousel is from this npm package: https://www.npmjs.com/package/react-responsive-carousel .

image

### CODE REVIEW

**Comment by Brian-Magnuson** [comment]
Currently, the image carousel is designed to span the entire width of the screen and be 600px tall. If the image is too big, it is resized via the `object-fit: cover` CSS property. A limitation I noticed was how right-clicking the image accesses the image *behind* the carousel, which is currently the background image for the page. Also, while adding the image, I noticed that the background image has a limited height and eventually cuts off revealing the gradient behind.

**Review by WillBAnders — APPROVED** [review]
@Brian-Magnuson Added a few commits to address review comments; most of which we discussed earlier:

 - Rename files to use lowercase extensions (a: consistency, b: matches the name used in the source code). This avoid any risks involve case-sensitivity.
 - Using `pointer-events: auto` allows the image to be interacted with; so this resolves the concern of the "View full image" piece.
 - Capped the max-width at `100vw / 2` to force a reasonable aspect ratio for the carousel/images. This avoids weird rendering due to the one portrait oriented image. This is far from ideal but I'm inclined to take the solution for now rather than iterate further; can open an issue to revisit it if you're inclined.

If these all seem good for the time being, let's go ahead and merge to close this out. Others can pick up trying to improve this next semester as desired.

Before vs After: Not amazing, but doesn't look weird.
image
image

**Comment by Brian-Magnuson** [comment]
Looks good. I made one last-minute change: I found out that if you add the `preventMovementUntilSwipeScrollTolerance` prop to the `ImageCarousel`, it improves scrolling on mobile (Google Chrome). That is, touching the carousel will still allow vertical scrolling on the page.
`pointer-events: auto` is pretty neat. I never knew that could work.
Will merge shortly. Thank you!

**Comment by WillBAnders** [comment]
I didn't know about `pointer-events: auto` either; I was looking through the styles via inspector and found `pointer-events: none` was being added by the library and disabling that solved the problem.

**Pull request merged**
